# AutoRNA main Snakefile (QC + Alignment)

configfile: "../config.yaml"

SAMPLES = config["samples"]

rule all:
    input:
        expand("data/aligned/{sample}.bam", sample=SAMPLES)

include: "rules/qc.smk"
include: "rules/align.smk"
